<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-H0PI4DT" failures="3" tests="12" name="Test" time="24.77" errors="0" timestamp="2022-06-21T16:45:04 IST">
  <testcase classname="retryLogicExample.HRMLoginTest" name="login" time="5.24"/>
  <testcase classname="retryLogicExample.HRMLoginTest" name="logout" time="3.038">
    <skipped/>
  </testcase> <!-- logout -->
  <testcase classname="retryLogicExample.HRMLoginTest" name="logout" time="2.117">
    <skipped/>
  </testcase> <!-- logout -->
  <testcase classname="retryLogicExample.HRMLoginTest" name="logout" time="2.7">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicExample.HRMLoginTest.logout(HRMLoginTest.java:88)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- logout -->
  <testcase classname="retryLogicExample.AmazonTest" name="addItems" time="0.002">
    <skipped/>
  </testcase> <!-- addItems -->
  <testcase classname="retryLogicExample.AmazonTest" name="addItems" time="0.002">
    <skipped/>
  </testcase> <!-- addItems -->
  <testcase classname="retryLogicExample.AmazonTest" name="addItems" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicExample.AmazonTest.addItems(AmazonTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addItems -->
  <testcase classname="retryLogicExample.AmazonTest" name="checkout" time="0.009"/>
  <testcase classname="retryLogicExample.AmazonTest" name="payment" time="0.008">
    <skipped/>
  </testcase> <!-- payment -->
  <testcase classname="retryLogicExample.AmazonTest" name="payment" time="0.001">
    <skipped/>
  </testcase> <!-- payment -->
  <testcase classname="retryLogicExample.AmazonTest" name="payment" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicExample.AmazonTest.payment(AmazonTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- payment -->
  <testcase classname="retryLogicExample.AmazonTest" name="serachItem" time="0.003"/>
</testsuite> <!-- Test -->
